# Generated by Django 3.0.3 on 2020-07-04 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('vacancy_count', models.IntegerField()),
                ('applicants_count', models.IntegerField(blank=True, null=True)),
                ('screening_ideal_fit_progress', models.IntegerField(blank=True, null=True)),
                ('upload_source', models.CharField(blank=True, max_length=200, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('user_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posting_user_r', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField()),
                ('is_current', models.BooleanField()),
                ('is_completed', models.BooleanField()),
                ('job_posting_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_status_posting_r', to='job_posting.JobPosting')),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_skillset', models.TextField()),
                ('skillset_gravity', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('preferred_institution', models.TextField(blank=True, null=True)),
                ('education_background', models.TextField()),
                ('required_education_level', models.TextField()),
                ('education_gravity', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('relevant_experience', models.TextField()),
                ('experience_gravity', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('relevant_professional_certifications', models.TextField(blank=True, null=True)),
                ('age_requirement', models.TextField(blank=True, null=True)),
                ('held_position', models.TextField(blank=True, null=True)),
                ('job_posting_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_description_posting_r', to='job_posting.JobPosting')),
            ],
        ),
    ]
