# Generated by Django 3.0.3 on 2020-07-04 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GetHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('help_type', models.TextField(max_length=10)),
                ('user_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_help_user_r', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
