# Generated by Django 3.0.3 on 2020-07-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('job_posting_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_job_posting_r', to='job_posting.JobPosting')),
            ],
        ),
    ]
