# Generated by Django 3.0.3 on 2020-07-25 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('secondary_email', models.EmailField(max_length=250)),
                ('organization', models.CharField(max_length=250)),
                ('employee_count', models.IntegerField()),
                ('office_address', models.TextField(max_length=650)),
                ('membership_plan', models.CharField(max_length=50)),
            ],
        ),
    ]
